package com.university.skilllink.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.index.Indexed;
import java.time.LocalDateTime;
/**
 * SessionBoard Entity - Represents a virtual classroom for learning sessions
 * This model serves as the communication space between learners and teachers
 * Each SessionBoard is created automatically when a skill request is accepted
 * 
 * Key Features:
 * - Links learners and teachers for specific learning sessions
 * - Supports meeting scheduling and progress tracking
 * - Trades communication history through linked messages
 * 
 * @author Member3 - Session Management Module
 * @version 1.0
 */

@Document(collection = "session_boards")
@Data
public class SessionBoard {
    @Id
    private String id;  // Primary key - auto-generated by MongoDB
    
    @Indexed(unique = true)
    private String sessionId; // References learning_sessions._id
    
    private String learnerId; // References users._id
    private String teacherId; // References users._id
    
    private LocalDateTime meetingDateTime; // Scheduled date and time for the learnin
    private String meetingLocation; // Virtual meeting link or physical location
    
    private String progressNotes;// Shared notes about learning progress and milestones
    
    private LocalDateTime lastMessageAt;
    private LocalDateTime createdAt;// Record creation timestamp
    private LocalDateTime updatedAt;// Last modification timestamp
}