package com.university.skilllink.dto.Message;

import lombok.Data;
import java.time.LocalDateTime;

@Data
public class MessageDTO {
    private String id;              // Auto-generated by MongoDB
    private String sessionBoardId;  // Which session board this belongs to
    private String senderId;  
    private String senderName;      // Who sent the message
    private String content;         // Message text
    private String messageType;     // TEXT, MEETING_SCHEDULE, etc.
    private Boolean isRead;         // Read status
    private LocalDateTime timestamp;// When sent
}